# Generated by Django 2.1 on 2018-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geodjango', '0002_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='mpoint',
            new_name='geom',
        ),
    ]
