# Generated by Django 2.1 on 2019-02-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geodjango', '0003_auto_20181130_1520'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='places',
            table='places',
        ),
        migrations.AlterModelTable(
            name='worldborder',
            table='worldborder',
        ),
    ]
