# Generated by Django 2.1 on 2019-02-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
